name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker_image:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    env:
      IMAGENAME: ${{ vars.DOCKER_REGISTRY }}/fumble:${{ github.ref_name }}
      BUILD_NAME: ${{ vars.GITHUB_REF_NAME }}
      BUILD_HASH: ${{ vars.GITHUB_SHA }}
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: "Install dependencies"
      run: 'npm ci'

    - name: "Run tests"
      run: 'npm run vitest run'

    - name: Build the Software
      run: 'npm run build'

    - name: Build the Docker image
      run: docker build --tag $IMAGENAME .

    - name: Log in to the Docker registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login "${{ vars.DOCKER_REGISTRY }}" -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

    - name: Push the Docker image
      run: docker push $IMAGENAME
